# Generated by Django 6.0.5 on 2026-05-21 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='NIN must start with CM (male) or CF (female)', regex='^(CM|CF)[A-Z0-9]{10,}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Ugandan number: 07XXXXXXXXX or +2567XXXXXXXX', regex='^(\\+256|0)(7)\\d{8}$')]),
        ),
    ]
