# Generated by Django 6.0.5 on 2026-05-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
